### ISSUE TITLE
Let's create a wireframe 

### ISSUE THREAD

**Issue by RustyRaptor** [alexismen22a/ITS#3]
Let's create a very simple wireframe of what we want the GUI to look. 
We can use something like Pencil Project to sketch it out. Then we can add a picture of it to our readme. 
https://pencil.evolus.vn/

Once we have a wireframe it will help us determine requirements and design.

**Comment by alexismen22a** [comment]
Wire frame IP

**Comment by RustyRaptor** [comment]
Completed https://github.com/alexismen22a/ITS/wiki
